# Site Info
title: DATA-MAGIC
tagline: 'AI 연구, 개발 관련 Blog : Til I Learned '
description: 'Python을 활용한 데이터 연구 및 세상 공부'
baseurl: ""
url: http://hwangyoungjoon.github.io
logo: '/public/logo.png'
encoding: utf-8

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty


version: 1.0.0

# About/contact
author:
  name: DATA_MAGICIAN
  description: 쟤보단 열심히 살고 있어에서 <strong>쟤</strong>를 맡고 있습니다. 
  gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
    github:    https://github.com/hwangyoungjoon
    email:     mghysoka@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/blog/'
  Study:           
    - '/'
    #- { Categories: '/blog/categories/' }
    #- { Tags: '/blog/tags/' }
    - { deep-leaning : '/blog/categories/#deeplearning' }
    - { algorithms : '/blog/categories/#algorithms' }
    - { machine-learning : '/blog/categories/#machine-learing' }
    - { github manage : '/blog/categories/#git-manage' }
  About:          
    - '/about/'
  # Contact: 
  #   - '/search/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/water.jpg
  #caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'Developer & researcher Hwang' # leave blank if you don't want disqus

gems:
  - jekyll-paginate